[project]
name = "controlsystems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "mypy>=1.14.1",
    "numpy>=2.2.1",
]

[mypy]
plugins = "numpy.typing.mypy_plugin"
